[versions]
agp = "8.1.0"
kotlin = "1.9.21"
kotlinx-kover = "0.7.4"

android-minSdk = "21"
android-compileSdk = "34"

nexus-publish = "2.0.0-rc-1"

[libraries]
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
