[versions]
plugin-kotlin = "1.9.0-Beta"

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "plugin-kotlin" }

[bundles]
plugins = [
    "plugin-kotlin",
]